### PR TITLE
move from travis to GitHub Actions

### PR DESCRIPTION
**Pull request by mansona**
Because Travis 😢 

I noticed that I made some changes in my PR that would probably have broken tests, but I noticed that tests aren't getting run on PRs. This fixes that 🎉

### CODE REVIEW

**Comment by mansona** [comment]
Also tests are failing too 🙃

**Comment by MelSumner** [comment]
Let's make todos or fix the issues, then merge. 

Also I invited you as a collab to make it easier. 👍

**Comment by MelSumner** [comment]
Update: I see what you mean by failing tests.  😓 I'll see if I can try to fix some of them.

**Review by MelSumner — APPROVED** [review]
going to get this merged but there's def some stuff on the sortable implementation that is broken, not sure how that is failing especially with so many tests.

**Pull request merged**
