### PR TITLE
Tidy up DOM: Index

### PR DESCRIPTION
**Pull request by Alonski**
This PR cleans up the index template a bit for #307 

First, I noticed that only the Developer icon had a hover effect on it. I fixed this by adding the hover effect to all cards.

Secondly I moved out the duplicated template code for each card into a separate component and utilized `ember-svg-jar` to move the SVGs into their own file instead of inline within the template.

This creates a much shorter index template and allows easier reusability incase more cards will be needed in the future. This would have also prevented the first point regarding the hover effect as all cards now use exactly the same CSS.

Would love thoughts and comments on this :)

### CODE REVIEW

**Comment by MelSumner** [comment]
@Alonski do you want to rebase this PR or should I close it?

**Comment by Alonski** [comment]
I can rebase @MelSumner :)

**Comment by Alonski** [comment]
@MelSumner Can I open a new PR to get Hacktoberfest credit? :)

**Comment by MelSumner** [comment]
@Alonski sure!

**Comment by Alonski** [comment]
Closing in favor of https://github.com/MelSumner/a11y-automation/pull/415

**Pull request closed without merging**
